In [1]:
import numpy as np

### Лабораторная №1

In [2]:
def inv_alg(A1, x, i):
    n = A1.shape[0]
    i -= 1

    l = A1 @ x
    if l[i] == 0:
        return 'The matrix is irreversible'
    _l = l.copy()
    _l[i] = -1

    l_check = (-1 / l[i]) * _l

    E = np.eye(n)
    Q = E.copy()
    Q[:, i] = l_check.T

    A1_res = np.zeros([n, n])
    for k in range(n):
        for j in range(n):
            A1_res[j][k] = Q[j][j] * A1[j][k] + Q[j][i] * A1[i][k]
            if j == i:
                A1_res[j][k] /= 2
                
    return A1_res

# A = np.array([[1, -1, 0],
#              [0, 1, 0],
#              [0, 0, 1]])
# A1 = np.array([[1, 1, 0],
#              [0, 1, 0],
#              [0, 0, 1]])
# x_A1 = np.array([[1],
#             [0],
#             [1]])
# i_A1 = 3

A = np.array([[1, 0, 0],
             [0, 1, 0],
             [0, 0, 1]])
A1 = np.array([[1, 0, 0],
             [0, 1, 0],
             [0, 0, 1]])
x_A1 = np.array([[-1],
            [1],
            [0]])
i_A1 = 2

B = np.array([[1, 3, 2],
             [4, 0, 6],
             [0, 1, 1]])
B1 = np.array([[0.6, 0.1, -1.8],
             [0.4, -0.1, -0.2],
             [-0.4, 0.1, 1.2]])
x_B1 = np.array([[1],
            [2],
            [0]])
i_B1 = 2

_A = A.copy()
_A[:, i_A1-1] = x_A1.T
print(f'With numpy:\n{np.linalg.inv(_A)}')
print(f'With algorithm:\n{inv_alg(A1, x_A1, i_A1)}')

_B = B.copy()
_B[:, i_B1-1] = x_B1.T
print(f'With numpy:\n{np.linalg.inv(_B)}')
print(f'With algorithm:\n{inv_alg(B1, x_B1, i_B1)}')

With numpy:
[[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
With algorithm:
[[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
With numpy:
[[-1.   0.5 -1. ]
 [ 2.  -0.5 -1. ]
 [ 0.   0.   1. ]]
With algorithm:
[[-1.   0.5 -1. ]
 [ 2.  -0.5 -1. ]
 [ 0.   0.   1. ]]


### Лабораторная №2

In [84]:
def simplex_main(c, A, b, x, _J):
    m = len(A)
    J = _J.copy()
    #STEP 1
    A_b = np.zeros([m, m])
    for i in range(len(J)):
        A_b[:, i] = A[:, J[i]-1]
    print(f'Step1: A_b:\n{A_b}')
    iteration = 1
    
    #STEP 2
    A_b_inv = np.linalg.inv(A_b)
    print(f'\nStep2: A_b_inv:\n{A_b_inv}')
    
    while True:
        #STEP 3
        print(f'Iteration №{iteration}:\n')
        c_b = np.array([c[J[i]-1] for i in range(len(J))])
        print(f'Step3: c_b={c_b}')
        
        #STEP 4
        u = c_b @ A_b_inv
        print(f'Step4: u={u}')
        
        #STEP 5
        delta = u @ A - c #repeat while all delta[i] become >= 0
        print(f'Step5: delta={delta}')        
        if min(delta) >= 0:
            #return f'Answer:{x}, J:{J}'
            return x, J
        
        #STEP 6
        for d in delta:
            if d < 0:
                j0 = list(delta).index(d)
                break

        z = np.zeros(len(J))
        z = A_b_inv @ A[:, j0]
        print(f'Step6: z={z}') 
        
        #STEP 7
        t = np.zeros(len(J))
        for i in range(len(J)):
            if z[i] > 0:
                t[i] = x[J[i]-1] / z[i]
            else:
                t[i] = np.inf
        t0 = min(t)
        print(f'Step7: t={t}; t0={t0}')
        if t0 == np.inf:
            return 'TARGET FUNCTION IS UNBOUNDED'
        
        #STEP 8
        t_index_for_j = list(t).index(t0)

        x_prev = x.copy()
        x = np.zeros(len(A[0]))
        
        J[t_index_for_j] = j0 + 1
        
        for i in range(len(J)):
            x[J[i] - 1] = x_prev[J[i] - 1] - t0 * z[i]
        x[j0] =  t0
        
        A_b_prev = A_b.copy()
        A_b[:, t_index_for_j] = A[:, j0]
        A_b_inv = inv_alg(np.linalg.inv(A_b_prev), A[:, j0], t_index_for_j + 1)
        
        print(f'Step8:\n t={t}, x={x}, J={J}, z={z}')
        print(f'A_b_inv:\n{A_b_inv}')
        print('##############')
        iteration += 1


#m, n = 4, 6
# A = np.array([[1, 2, 1, 0, 0, 0],
#              [2, 1, 0, 1, 0 ,0],
#              [1, 0, 0, 0, 1, 0],
#              [0, 1, 0, 0, 0, 1]])
# b = np.array([10, 11, 5, 4])
# c = np.array([20, 26, 0, 0, 0, 1])
# x = np.array([2, 4, 0, 3, 3, 0])
# J = np.array([5, 2, 1, 4])

# A = np.array([[-1, 1, 1, 0, 0],
#              [1, 0, 0, 1, 0],
#              [0, 1, 0, 0, 1]])
# b = np.array([1, 3, 2])
# c = np.array([1, 1, 0, 0, 0])
# x = np.array([0, 0, 1, 3, 2])
# J = np.array([3, 4, 5])

A = np.array([[2, 1, 1, 0, 0, 0],
             [1, 4, 0, 1, 0, 0],
             [1, 0, 0, 0, 1, 0],
             [0, 1, 0, 0, 0, 1]])
b = np.array([20, 24, 9, 5])
c = np.array([22, 21, 1, 0, 0, 0])
x = np.array([0, 0, 20, 24, 9, 5])
J = np.array([3, 4, 5, 6])
print(simplex_main(c, A, b, x, J))

Step1: A_b:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Step2: A_b_inv:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Iteration №1:

Step3: c_b=[1 0 0 0]
Step4: u=[1. 0. 0. 0.]
Step5: delta=[-20. -20.   0.   0.   0.   0.]
Step6: z=[2. 1. 1. 0.]
Step7: t=[10. 24.  9. inf]; t0=9.0
Step8:
 t=[10. 24.  9. inf], x=[ 9.  0.  2. 15.  0.  5.], J=[3 4 1 6], z=[2. 1. 1. 0.]
A_b_inv:
[[ 1.  0. -2.  0.]
 [ 0.  1. -1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
##############
Iteration №2:

Step3: c_b=[ 1  0 22  0]
Step4: u=[ 1.  0. 20.  0.]
Step5: delta=[  0. -20.   0.   0.  20.   0.]
Step6: z=[1. 4. 0. 1.]
Step7: t=[2.   3.75  inf 5.  ]; t0=2.0
Step8:
 t=[2.   3.75  inf 5.  ], x=[9. 2. 0. 7. 0. 3.], J=[2 4 1 6], z=[1. 4. 0. 1.]
A_b_inv:
[[ 1.  0. -2.  0.]
 [-4.  1.  7.  0.]
 [ 0.  0.  1.  0.]
 [-1.  0.  2.  1.]]
##############
Iteration №3:

Step3: c_b=[21  0 22  0]
Step4: u=[ 21.   0. -20.   0.]
Step5: delta=[  0.   0.  20.   0. -20.   0.]
Step6: z=[-2.  7.  1.  

### Лабораторная №3

In [220]:
# A = np.array([[2, 1, 1, 0, 0, 0],
#              [1, 4, 0, 1, 0, 0],
#              [1, 0, 0, 0, 1, 0],
#              [0, 1, 0, 0, 0, 1]])
# b = np.array([20, 24, 9, 5])
# c = np.array([22, 21, 1, 0, 0, 0])
# A = np.array([[2, 1, 1, 0, 0, 0],
#              [1, 3, 0, 1, 0, 0],
#              [1, 0, 0, 0, 1, 0],
#              [0, 1, 0, 0, 0, 1]])
# b = np.array([22, 21, 10, 6])
# c = np.array([20, 19, 0, 0, 0, -1])
A = np.array([[1, 1, 1],
            [2, 2, 2]])
b = np.array([0, 0])
c = np.array([1, 0, 0])


def begin_simplex(A, b, c):
    for i in range(len(b)):
        if b[i] < 0:
            A[i] *= -1
            b[i] *= -1
    n = len(c)
    m = len(b)
    J = np.array([i + 1 for i in range(n)])
    _c, _A, _x, _J, E = np.zeros(n + len(A)), A.copy(), np.zeros(n), \
                        np.array([]),  np.eye(len(A))

    _A, _x = np.concatenate((_A, E), axis=1), np.concatenate((_x, b))
    for i in range(len(A)):
        _c[n + i] = -1   

    for i in range(1, len(A) + 1):
        index = n + i
        _J = np.append(_J, index)
    print(f'_J:{_J}')
    _J = [int(_J[i]) for i in range(len(_J))]
    
    x_new, J_new = simplex_main(_c, _A, b, _x, _J)

    if not np.all(x_new[-m:] == 0):
        return f'TARGET FUNCTION IS UNBOUNDED: x:{x_new}'

    x_result = x_new[:n]
    print(f'J_new:{J_new}, _J:{_J}')
    if not set(J_new) & set(_J):
        return f'Answer is:\n J:{J_new},\n A*:\n{A},\n x*:{x_result}'
    else:
        J_art = np.array([])
        J_not_basis = J.copy()
        A_result = A.copy()
        _A_result = _A.copy()
        _c_result = _c.copy()    
        for j in J_new:
            if j not in J:
                J_art = np.append(J_art, j)
            if j in J:
                J_not_basis = np.setdiff1d(J_not_basis, j)

        for i in range(len(J_art)):
            k = list(J_new).index(J_art[i]) #####TODO: change 0  to i where i = [0, len(J_art)]

            l = np.zeros((len(J_not_basis), len(J_not_basis)))
            A_art_basis = np.zeros([len(J_new), len(J_new)])
            for i in range(len(J_new)):
                A_art_basis[:, i] = _A[:, J_new[i] - 1]

            A_art_basis_inv = np.linalg.inv(A_art_basis)
            for i in range(len(J_not_basis)):
                l[i] = A_art_basis_inv @ _A[:, J_not_basis[i] - 1]
            #print(l[:, 0][0])

            index = 0
            check = np.zeros(len(l))
            for vector in l:
                if vector[k] != 0:
                    J_new[k] = J_not_basis[index]   
                    check[index] = 1
                index += 1    
            if np.all(check == 0):
                J_new = np.delete(J_new, k)
                A_result = np.delete(A_result, k, axis = 0)
                _A_result = np.delete(_A_result, k, axis = 0)
                _c_result = np.delete(_c_result, n + k)
            if not set(J_new) & set(_J):
                return f'Answer:\n J:{J_new},\n A*:\n{A_result},\n x*:{x_result}'                
            
print(begin_simplex(A, b, c))

_J:[4. 5.]
Step1: A_b:
[[1. 0.]
 [0. 1.]]

Step2: A_b_inv:
[[1. 0.]
 [0. 1.]]
Iteration №1:

Step3: c_b=[-1. -1.]
Step4: u=[-1. -1.]
Step5: delta=[-3. -3. -3.  0.  0.]
Step6: z=[1. 2.]
Step7: t=[0. 0.]; t0=0.0
Step8:
 t=[0. 0.], x=[0. 0. 0. 0. 0.], J=[1, 5], z=[1. 2.]
A_b_inv:
[[ 1.  0.]
 [-2.  1.]]
##############
Iteration №2:

Step3: c_b=[ 0. -1.]
Step4: u=[ 2. -1.]
Step5: delta=[0. 0. 0. 3. 0.]
J_new:[1, 5], _J:[4, 5]
Answer:
 J:[1],
 A*:
[[1 1 1]],
 x*:[0. 0. 0.]
