In [2]:
import numpy as np

### Лабораторная №1

In [3]:
def inv_alg(A1, x, i):
    n = A1.shape[0]
    i -= 1

    l = A1 @ x
    if l[i] == 0:
        return 'The matrix is irreversible'
    _l = l.copy()
    _l[i] = -1

    l_check = (-1 / l[i]) * _l

    E = np.eye(n)
    Q = E.copy()
    Q[:, i] = l_check.T

    A1_res = np.zeros([n, n])
    for k in range(n):
        for j in range(n):
            A1_res[j][k] = Q[j][j] * A1[j][k] + Q[j][i] * A1[i][k]
            if j == i:
                A1_res[j][k] /= 2
                
    return A1_res

# A = np.array([[1, -1, 0],
#              [0, 1, 0],
#              [0, 0, 1]])
# A1 = np.array([[1, 1, 0],
#              [0, 1, 0],
#              [0, 0, 1]])
# x_A1 = np.array([[1],
#             [0],
#             [1]])
# i_A1 = 3

A = np.array([[1, 0, 0],
             [0, 1, 0],
             [0, 0, 1]])
A1 = np.array([[1, 0, 0],
             [0, 1, 0],
             [0, 0, 1]])
x_A1 = np.array([[-1],
            [1],
            [0]])
i_A1 = 2

B = np.array([[1, 3, 2],
             [4, 0, 6],
             [0, 1, 1]])
B1 = np.array([[0.6, 0.1, -1.8],
             [0.4, -0.1, -0.2],
             [-0.4, 0.1, 1.2]])
x_B1 = np.array([[1],
            [2],
            [0]])
i_B1 = 2

_A = A.copy()
_A[:, i_A1-1] = x_A1.T
print(f'With numpy:\n{np.linalg.inv(_A)}')
print(f'With algorithm:\n{inv_alg(A1, x_A1, i_A1)}')

_B = B.copy()
_B[:, i_B1-1] = x_B1.T
print(f'With numpy:\n{np.linalg.inv(_B)}')
print(f'With algorithm:\n{inv_alg(B1, x_B1, i_B1)}')

With numpy:
[[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
With algorithm:
[[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
With numpy:
[[-1.   0.5 -1. ]
 [ 2.  -0.5 -1. ]
 [ 0.   0.   1. ]]
With algorithm:
[[-1.   0.5 -1. ]
 [ 2.  -0.5 -1. ]
 [ 0.   0.   1. ]]


### Лабораторная №2

In [4]:
def simplex_main(c, A, b, x, _J):
    m = len(A)
    J = _J.copy()
    #STEP 1
    A_b = np.zeros([m, m])
    for i in range(len(J)):
        A_b[:, i] = A[:, J[i]-1]
    print(f'Step1: A_b:\n{A_b}')
    iteration = 1
    
    #STEP 2
    A_b_inv = np.linalg.inv(A_b)
    print(f'\nStep2: A_b_inv:\n{A_b_inv}')
    
    while True:
        #STEP 3
        print(f'Iteration №{iteration}:\n')
        c_b = np.array([c[J[i]-1] for i in range(len(J))])
        print(f'Step3: c_b={c_b}')
        
        #STEP 4
        u = c_b @ A_b_inv
        print(f'Step4: u={u}')
        
        #STEP 5
        delta = u @ A - c #repeat while all delta[i] become >= 0
        print(f'Step5: delta={delta}')        
        if min(delta) >= 0:
            #return f'Answer:{x}, J:{J}'
            return x, J
        
        #STEP 6
        for d in delta:
            if d < 0:
                j0 = list(delta).index(d)
                break

        z = np.zeros(len(J))
        z = A_b_inv @ A[:, j0]
        print(f'Step6: z={z}') 
        
        #STEP 7
        t = np.zeros(len(J))
        for i in range(len(J)):
            if z[i] > 0:
                t[i] = x[J[i]-1] / z[i]
            else:
                t[i] = np.inf
        t0 = min(t)
        print(f'Step7: t={t}; t0={t0}')
        if t0 == np.inf:
            return 'TARGET FUNCTION IS UNBOUNDED'
        
        #STEP 8
        t_index_for_j = list(t).index(t0)

        x_prev = x.copy()
        x = np.zeros(len(A[0]))
        
        J[t_index_for_j] = j0 + 1
        
        for i in range(len(J)):
            x[J[i] - 1] = x_prev[J[i] - 1] - t0 * z[i]
        print(f'x_before:{x_prev}')
        x[j0] =  t0
        
        A_b_prev = A_b.copy()
        A_b[:, t_index_for_j] = A[:, j0]
        A_b_inv = inv_alg(np.linalg.inv(A_b_prev), A[:, j0], t_index_for_j + 1)
        
        print(f'Step8:\n t={t}, x={x}, J={J}, z={z}')
        print(f'A_b_inv:\n{A_b_inv}')
        print('##############')
        iteration += 1


#m, n = 4, 6
# A = np.array([[1, 2, 1, 0, 0, 0],
#              [2, 1, 0, 1, 0 ,0],
#              [1, 0, 0, 0, 1, 0],
#              [0, 1, 0, 0, 0, 1]])
# b = np.array([10, 11, 5, 4])
# c = np.array([20, 26, 0, 0, 0, 1])
# x = np.array([2, 4, 0, 3, 3, 0])
# J = np.array([5, 2, 1, 4])

# A = np.array([[-1, 1, 1, 0, 0],
#              [1, 0, 0, 1, 0],
#              [0, 1, 0, 0, 1]])
# b = np.array([1, 3, 2])
# c = np.array([1, 1, 0, 0, 0])
# x = np.array([0, 0, 1, 3, 2])
# J = np.array([3, 4, 5])

A = np.array([[2, 1, 1, 0, 0, 0],
             [1, 4, 0, 1, 0, 0],
             [1, 0, 0, 0, 1, 0],
             [0, 1, 0, 0, 0, 1]])
b = np.array([20, 24, 9, 5])
c = np.array([22, 21, 1, 0, 0, 0])
x = np.array([0, 0, 20, 24, 9, 5])
J = np.array([3, 4, 5, 6])
print(simplex_main(c, A, b, x, J))

Step1: A_b:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Step2: A_b_inv:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Iteration №1:

Step3: c_b=[1 0 0 0]
Step4: u=[1. 0. 0. 0.]
Step5: delta=[-20. -20.   0.   0.   0.   0.]
Step6: z=[2. 1. 1. 0.]
Step7: t=[10. 24.  9. inf]; t0=9.0
x_before:[ 0  0 20 24  9  5]
Step8:
 t=[10. 24.  9. inf], x=[ 9.  0.  2. 15.  0.  5.], J=[3 4 1 6], z=[2. 1. 1. 0.]
A_b_inv:
[[ 1.  0. -2.  0.]
 [ 0.  1. -1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
##############
Iteration №2:

Step3: c_b=[ 1  0 22  0]
Step4: u=[ 1.  0. 20.  0.]
Step5: delta=[  0. -20.   0.   0.  20.   0.]
Step6: z=[1. 4. 0. 1.]
Step7: t=[2.   3.75  inf 5.  ]; t0=2.0
x_before:[ 9.  0.  2. 15.  0.  5.]
Step8:
 t=[2.   3.75  inf 5.  ], x=[9. 2. 0. 7. 0. 3.], J=[2 4 1 6], z=[1. 4. 0. 1.]
A_b_inv:
[[ 1.  0. -2.  0.]
 [-4.  1.  7.  0.]
 [ 0.  0.  1.  0.]
 [-1.  0.  2.  1.]]
##############
Iteration №3:

Step3: c_b=[21  0 22  0]
Step4: u=[ 21.   0. -20.   0.]
Step

### Лабораторная №3

In [13]:
# A = np.array([[2, 1, 1, 0, 0, 0],
#              [1, 4, 0, 1, 0, 0],
#              [1, 0, 0, 0, 1, 0],
#              [0, 1, 0, 0, 0, 1]])
# b = np.array([20, 24, 9, 5])
# c = np.array([22, 21, 1, 0, 0, 0])
# A = np.array([[2, 1, 1, 0, 0, 0],
#              [1, 3, 0, 1, 0, 0],
#              [1, 0, 0, 0, 1, 0],
#              [0, 1, 0, 0, 0, 1]])
# b = np.array([22, 21, 10, 6])
# c = np.array([20, 19, 0, 0, 0, -1])
# A = np.array([[1, 1, 1],
#             [2, 2, 2]])
# b = np.array([0, 0])
# c = np.array([1, 0, 0])
#22
# A = np.array([[-2, 3, 1, 0],
#              [4, 3, 0, 1],
#              [0, 9, 2, 1]])
# b = np.array([6, 24, 36])
#20
# A = np.array([[-1, 3, 1, 0, 0],
#              [1, 1, 0, 1, 0],
#              [0, -1, 0, 0, 1]])
# b = np.array([3, 5, -3])
#21
A = np.array([[-1, 3, 1, 0],
             [3, 2, 0, 1],
             [1, 8, 2, 1]])
b = np.array([6, 15, 27])
# print(f'A:\n{A}')
# print(f'b:\n{b}')
#28
# A = np.array([[-1, 6, 1, 0],
#              [4, 1, 0, 1],
#              [3, 7, 1, 1]])
# b = np.array([18, 28, 46])


def simplex_begin(A, b):
    for i in range(len(b)):
        if b[i] < 0:
            A[i] *= -1
            b[i] *= -1
            
    n = len(A[0])    
    m = len(b)
    J = np.array([i + 1 for i in range(n)])
    _c, _A, _x, _J, E = np.zeros(n + len(A)), A.copy(), np.zeros(n), \
                        np.array([]),  np.eye(len(A))

    _A, _x = np.concatenate((_A, E), axis=1), np.concatenate((_x, b))
    print(f'_x={_x}')
    for i in range(len(A)):
        _c[n + i] = -1   

    for i in range(1, len(A) + 1):
        index = n + i
        _J = np.append(_J, index)
    print(f'_J:{_J}')
    _J = [int(_J[i]) for i in range(len(_J))]
    
    x_new, J_new = simplex_main(_c, _A, b, _x, _J)

    if not np.all(x_new[-m:] == 0):
        return f'TARGET FUNCTION IS UNBOUNDED: x:{x_new}'

    x_result = x_new[:n]
    print(f'x_new:{x_new}')
    print(f'x_result:{x_result}')
    print(f'J_new:{J_new}, _J:{_J}')
    if not set(J_new) & set(_J):
        return f'Answer is:\n J:{J_new},\n A*:\n{A},\n x*:{x_result}'
    else:
        J_art = np.array([])
        J_not_basis = J.copy()
        A_result = A.copy()
        _A_result = _A.copy()
        _c_result = _c.copy()    
        for j in J_new:
            if j not in J:
                J_art = np.append(J_art, j)
            if j in J:
                J_not_basis = np.setdiff1d(J_not_basis, j)
        it = 1
        for i in range(len(J_art)):
            print(f'\nIteration {it}:')
            k = list(J_new).index(J_art[i]) #####TODO: change 0  to i where i = [0, len(J_art)]

            l = np.zeros((len(J_new), len(J_new)))
            A_art_basis = np.zeros([len(J_new), len(J_new)])
            for i in range(len(J_new)):
                A_art_basis[:, i] = _A[:, J_new[i] - 1]

            A_art_basis_inv = np.linalg.inv(A_art_basis)
            print(f'_A:\n{_A}')
            print(f'A_art_basis:\n{A_art_basis}')
            print(f'A_art_basis_inv:\n{A_art_basis_inv}')
            for i in range(len(J_not_basis)):
                l[i] = A_art_basis_inv @ _A[:, J_not_basis[i] - 1]
                print(f'_A[:, J_not_basis[i] - 1]={_A[:, J_not_basis[i] - 1]}')
                print(f'l[i]={l[i]}')
            #print(l[:, 0][0])

            index = 0
            check = np.zeros(len(l))
            for vector in l:
                if vector[k] != 0:
                    J_new[k] = J_not_basis[index]   
                    check[index] = 1
                index += 1    
            if np.all(check == 0):
                J_new = np.delete(J_new, k)
                A_result = np.delete(A_result, k, axis = 0)
                _A_result = np.delete(_A_result, k, axis = 0)
                _c_result = np.delete(_c_result, n + k)
            if not set(J_new) & set(_J):
                return f'Answer:\n J:{J_new},\n A*:\n{A_result},\n x*:{x_result}'                
            
print(simplex_begin(A, b))

_x=[ 0.  0.  0.  0.  6. 15. 27.]
_J:[5. 6. 7.]
Step1: A_b:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Step2: A_b_inv:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Iteration №1:

Step3: c_b=[-1. -1. -1.]
Step4: u=[-1. -1. -1.]
Step5: delta=[ -3. -13.  -3.  -2.   0.   0.   0.]
Step6: z=[-1.  3.  1.]
Step7: t=[inf  5. 27.]; t0=5.0
x_before:[ 0.  0.  0.  0.  6. 15. 27.]
Step8:
 t=[inf  5. 27.], x=[ 5.  0.  0.  0. 11.  0. 22.], J=[5, 1, 7], z=[-1.  3.  1.]
A_b_inv:
[[ 1.          0.33333333  0.        ]
 [ 0.          0.33333333  0.        ]
 [ 0.         -0.33333333  1.        ]]
##############
Iteration №2:

Step3: c_b=[-1.  0. -1.]
Step4: u=[-1.  0. -1.]
Step5: delta=[  0. -11.  -3.  -1.   0.   1.   0.]
Step6: z=[3.66666667 0.66666667 7.33333333]
Step7: t=[3.  7.5 3. ]; t0=3.0
x_before:[ 5.  0.  0.  0. 11.  0. 22.]
Step8:
 t=[3.  7.5 3. ], x=[3. 3. 0. 0. 0. 0. 0.], J=[2, 1, 7], z=[3.66666667 0.66666667 7.33333333]
A_b_inv:
[[ 0.27272727  0.09090909  0.        ]
 [-0.18181818  0.27272727  0.        ]


### Лабораторная №4

In [16]:
def double_simplex(A, b, c, J):
    #prepare
    m = len(A)
    n = len(A[0])
    A_b = np.zeros([m, m])
    for i in range(len(J)):
        A_b[:, i] = A[:, J[i] - 1]

    A_b_inv = np.linalg.inv(A_b)
    c_b = np.array([c[J[i]-1] for i in range(len(J))])
    y = c_b @ A_b_inv
    print(f'A_b:\n{A_b}')
    print(f'A_b_inv:\n{A_b_inv}')
    print(f'c_b={c_b}')
    print(f'y={y}')

    it = 1
    while True:
        print(f'\nIteration = {it}')
        #STEP 1
        print(f'A_b_inv:\n{A_b_inv}')
        ae = np.zeros(n)
        ae_b = A_b_inv @ b
        for i in range(len(ae_b)):
            ae[J[i] - 1] = ae_b[i]

        if min(ae) >= 0:
            return(f'Answer: {ae}') 
        print(f'ae = {ae}')
        
        loc_min = min(ae)
        
        ind = list(ae).index(loc_min) + 1
        
        print(ind)
        index_of_row = list(J).index(ind)
        print(f'index_of_row = {index_of_row+1}')
        delta_y = A_b_inv[index_of_row]
        print(f'delta_y = {delta_y}')

        #STEP 2
        indexes = np.arange(n) + 1
        J_nb = np.array([])
        for i in indexes:
            if i not in J:
                J_nb = np.append(J_nb, i)
        print(f'J_nb = {J_nb}')
        mu = np.array([delta_y @ A[:, int(J_nb[i]) - 1] for i in range(len(J_nb))])
        print(f'mu = {mu}')
        
        #STEP 3
        if min(mu) >= 0:
            return 'no solutions' 

        sigma = []
        sigma_indx = []
        
        for i in range(len(mu)):
            if mu[i] < 0:
                j = int(J_nb[i] - 1)
                sgm = (c[j] - A[:, j] @ y) / mu[i]
                sigma.append(sgm)
                sigma_indx.append(j)
        print(f'sigma = {sigma}')
        sgm0 = min(sigma)
        j_indx = sigma.index(sgm0)
        index_sgm0 = sigma_indx[j_indx] + 1
        print(f'index_sgm0 = {index_sgm0}')

        #STEP 4
        J[index_of_row] = index_sgm0
        y += sgm0 * delta_y
        print(f'y = {y}')
        print(f'J = {J}')
        for i in range(len(J)):
            A_b[:, i] = A[:, J[i] - 1]
        print(f'A_b:\n{A_b}')
        A_b_inv = np.linalg.inv(A_b)
        print(f'A_b_inv:\n{A_b_inv}')       
        it += 1

c = np.array([-4, 2, 0, 1])
A = np.array([[-1, -3, 1, 1],
             [-2, 3, 0, 1]])

b = np.array([-12, -6])
J = np.array([3, 4])

print(double_simplex(A, b, c, J))

A_b:
[[1. 1.]
 [0. 1.]]
A_b_inv:
[[ 1. -1.]
 [ 0.  1.]]
c_b=[0 1]
y=[0. 1.]

Iteration = 1
A_b_inv:
[[ 1. -1.]
 [ 0.  1.]]
ae = [ 0.  0. -6. -6.]
3
index_of_row = 1
delta_y = [ 1. -1.]
J_nb = [1. 2.]
mu = [ 1. -6.]
sigma = [0.16666666666666666]
index_sgm0 = 2
y = [0.16666667 0.83333333]
J = [2 4]
A_b:
[[-3.  1.]
 [ 3.  1.]]
A_b_inv:
[[-0.16666667  0.16666667]
 [ 0.5         0.5       ]]

Iteration = 2
A_b_inv:
[[-0.16666667  0.16666667]
 [ 0.5         0.5       ]]
ae = [ 0.  1.  0. -9.]
4
index_of_row = 2
delta_y = [0.5 0.5]
J_nb = [1. 3.]
mu = [-1.5  0.5]
sigma = [1.4444444444444444]
index_sgm0 = 1
y = [0.88888889 1.55555556]
J = [2 1]
A_b:
[[-3. -1.]
 [ 3. -2.]]
A_b_inv:
[[-0.22222222  0.11111111]
 [-0.33333333 -0.33333333]]

Iteration = 3
A_b_inv:
[[-0.22222222  0.11111111]
 [-0.33333333 -0.33333333]]
Answer: [6. 2. 0. 0.]


### Лабораторная №5 

In [151]:
# a = [100, 300, 300]
# b = [300, 200, 200]
# c = np.array([[8, 4, 1],
#              [8, 4, 3],
#              [9, 7, 5]])
# a = [50, 70, 80, 100, 110, 200, 250]
# b = [20, 80, 90, 90, 130, 150, 300]
# c = np.array([[5, 6, 11, 4, 9, 13, 10],
#              [3, 7, 8, 1, 12, 9, 8],
#              [10, 4, 9, 7, 3, 4, 5],
#              [2, 6, 8, 3, 7, 19, 2],
#              [7, 9, 11, 6, 4, 3, 8],
#              [2, 3, 7, 16, 14, 5, 1],
#              [17, 6, 2, 5, 6, 2, 8]])

#5(mine)
# a = [50, 70, 80]
# b = [20, 90, 90]
# c = np.array([[5, 6, 11],
#              [3, 7, 8],
#              [10, 4, 9]])

#14
# a = [100, 70, 170]
# b = [140, 100, 100]
# c = np.array([[1, 5, 6],
#              [2, 3, 2],
#              [4, 1, 1]])

#11
# a = [50, 170, 80]
# b = [200, 50, 50]
# c = np.array([[2, 5, 6],
#              [3, 4, 3],
#              [6, 1, 2]])
def transport_problem(a, b, c):
    m, n = len(a), len(b)
    X = np.zeros([m, n])
    J = []
    i, j = 0, 0
    
    #PHASE 1
    while True:
        if sum(a) == 0 and sum(b) == 0:
            break
        if a[i] < b[j]:
            X[i][j] = a[i]
            b[j] -= a[i]
            a[i] = 0
            J.append([i, j])
            i += 1
        else:
            X[i][j] = b[j]
            a[i] -= b[j]
            b[j] = 0
            J.append([i, j])
            j += 1
    print(f'X before 2nd phase:\n{X}')        
    #PHASE 2
    it = 1
    while True:
        print(f'\nIteration {it}\n')
        UV = np.zeros([n + m, n + m])
        for i in range(len(J)):
            UV[i][J[i][0]] = 1    
            UV[i][J[i][1] + m] = 1
        UV[-1][0] = 1
        print(f'UV:\n{UV}')
        b_uv = [c[J[i][0]][J[i][1]] for i in range(len(J))]    
        b_uv.append(0)
        print(f'b_uv:{b_uv}]')
        uv = np.linalg.solve(UV, b_uv)
        u = uv[:m]
        v = uv[-n:]
        print(f'u:{u}; v:{v}')
        positions = []
        for i in range(m):
            for j in range(n):
                positions.append([i, j])

        J_not_basis = []
        for p in positions:
            if p not in J:
                J_not_basis.append(p)
        print(f'J_not_basis:{J_not_basis}')
        pos = []
        quit = True
        for p in J_not_basis:
            if u[p[0]] + v[p[1]] > c[p[0]][p[1]]:
                quit = False
                pos = p
                break
        print(pos)
        if quit:
            print(f'Answer:')
            return X
            

        for p in J:
            if n * p[0] + 1 + p[1] > n * pos[0] + 1 + pos[1]: #n or m?
                index = J.index(p)
                temp_pos = pos.copy()
                J.insert(index, temp_pos)
                print(f'J with new pos:{J}')
                break

        #здесь ненужные строки/столбцы будут обнулятся
        #вместо удаления (это нужно для правильного определения позиции)
        basis_matrix = np.zeros([m, n])
        for p in J:
            basis_matrix[p[0]][p[1]] = 1

        
        #для видимого удаления строк/столбцов
        basis_matrix_copy = basis_matrix.copy()
        print(f'before del:\n{basis_matrix_copy}')
        deleted = False
        while True:
            deleted = False
            for i in range(len(basis_matrix)):
                if 0 < sum(basis_matrix[i]) < 2:
                    basis_matrix[i] = np.zeros(len(basis_matrix[0]))
                    deleted = True
                    break
            for i in range(len(basis_matrix[0])):
                 if 0 < sum(basis_matrix[:, i]) < 2:
                    basis_matrix[:, i] = np.zeros(len(basis_matrix))
                    deleted = True
                    break
            if not deleted:
                break
        deleted = False
        t_pos = []
        while True:
            deleted = False
            for i in range(len(basis_matrix_copy)):
                if 0 < sum(basis_matrix_copy[i]) < 2:
                    basis_matrix_copy = np.delete(basis_matrix_copy, i, axis=0)
                    deleted = True
                    break
            for i in range(len(basis_matrix_copy[0])):
                 if 0 < sum(basis_matrix_copy[:, i]) < 2:
                    basis_matrix_copy = np.delete(basis_matrix_copy, i, axis=1)                
                    deleted = True
                    break
            if not deleted:
                break
        print(f'after del:\n{basis_matrix_copy}')
        print(f'basis_matrix:\n{basis_matrix}')
        J_angle = []
        for i in range(len(basis_matrix)):
            for j in range(len(basis_matrix[0])):
                if basis_matrix[i][j] == 1:
                    J_angle.append([i, j])
        print(f'J angle only:\n{J_angle}')

        sign_matrix = np.full(basis_matrix.shape, '.')
        sign_matrix[pos[0]][pos[1]] = '+'
        cur_pos = pos
        print(f'pos={pos}')
        going_column = True
        all_signs = ['+']
        all_minus = []
        for i in range(len(J_angle)):
            while True:            
                for p in J_angle:
                    if (p[0] == cur_pos[0] and p[1] != cur_pos[1] or p[0] != cur_pos[0] and p[1] == cur_pos[1]) \
                        and sign_matrix[p[0]][p[1]] == '.':
                        cur_pos = p
                        print(cur_pos)
                        if all_signs[-1] == '+':
                            sign_matrix[cur_pos[0]][cur_pos[1]] = '-'
                            all_signs.append('-')
                            all_minus.append(X[cur_pos[0]][cur_pos[1]])
                        else:
                            sign_matrix[cur_pos[0]][cur_pos[1]] = '+'
                            all_signs.append('+')                    
                        break
                break

        print(f'all_minus:{all_minus}')
        teta = min(all_minus)
        print(f'teta:{teta}')
        print(f'sign_matrix:\n{sign_matrix}')
        for i in range(len(X)):
            for j in range(len(X[0])):
                if sign_matrix[i][j] == '-':
                    X[i][j] -= teta
                if sign_matrix[i][j] == '+':
                    X[i][j] += teta
        finish = False
        print(f'new X:\n{X}')
        for i in range(len(X)):
            for j in range(len(X[0])):
                if X[i][j] == 0 and [i, j] in J:
                    pos_min = [i, j]
                    J.remove(pos_min)
                    finish = True
                    break
            if finish:
                break

        print(f'new J: {J}')
        it += 1

#5(mine)
a = [50, 70, 80]
b = [20, 90, 90]
c = np.array([[5, 6, 11],
             [3, 7, 8],
             [10, 4, 9]])
transport_problem(a, b, c)



X before 2nd phase:
[[20. 30.  0.]
 [ 0. 60. 10.]
 [ 0.  0. 80.]]

Iteration 1

UV:
[[1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]
b_uv:[5, 6, 7, 8, 9, 0]]
u:[0. 1. 2.]; v:[5. 6. 7.]
J_not_basis:[[0, 2], [1, 0], [2, 0], [2, 1]]
[1, 0]
J with new pos:[[0, 0], [0, 1], [1, 0], [1, 1], [1, 2], [2, 2]]
before del:
[[1. 1. 0.]
 [1. 1. 1.]
 [0. 0. 1.]]
after del:
[[1. 1.]
 [1. 1.]]
basis_matrix:
[[1. 1. 0.]
 [1. 1. 0.]
 [0. 0. 0.]]
J angle only:
[[0, 0], [0, 1], [1, 0], [1, 1]]
pos=[1, 0]
[0, 0]
[0, 1]
[1, 1]
all_minus:[20.0, 60.0]
teta:20.0
sign_matrix:
[['-' '+' '.']
 ['+' '-' '.']
 ['.' '.' '.']]
new X:
[[ 0. 50.  0.]
 [20. 40. 10.]
 [ 0.  0. 80.]]
new J: [[0, 1], [1, 0], [1, 1], [1, 2], [2, 2]]

Iteration 2

UV:
[[1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]
b_uv:[6, 3, 7, 8, 9, 0]]
u:[0. 1. 2.]; v:[2. 6. 7.]
J_not_basis:[[0, 0], [

array([[20., 30.,  0.],
       [ 0.,  0., 70.],
       [ 0., 60., 20.]])

In [148]:
import numpy as np


def extend(a, b, c):
    a_extended = np.array(a)
    b_extended = np.array(b)
    c_extended = np.array(c)

    sa = sum(a)
    sb = sum(b)
    print(c_extended.shape, np.zeros((len(a), 1)))
    if sa > sb:
        b_extended = np.append(b_extended, sa - sb)
        c_extended = np.hstack((c_extended, np.zeros((len(a), 1))))
    else:
        a_extended = np.append(a_extended, sb - sa)
        c_extended = np.vstack((c_extended, np.zeros(len(b))))
    return a_extended, b_extended, c_extended


def build_X_north_west(a, b):
    m = len(a)
    n = len(b)
    x = np.zeros((m, n))
    J = []

    cur_a = np.copy(a)
    cur_b = np.copy(b)
    i, j = 0, 0
    while i < m:
        while j < n:
            min_val = min(cur_a[i], cur_b[j])
            x[i][j] = min_val
            cur_a[i] -= min_val
            cur_b[j] -= min_val
            J.append((i, j))
            if not cur_a[i]:
                i += 1
                break
            j += 1

    return x, J


def get_potentials(x, c, J):
    m, n = np.shape(x)

    a = np.zeros((m + n, m + n))
    b = np.zeros(m + n)

    k = 1
    for i, j in J:
        print('u[{}] + v[{}] = {}'.format(i, j, c[i][j]))

        a[k][i] = 1
        a[k][j + m] = 1
        b[k] = c[i][j]
        k += 1

    a[0][0] = 1
    print(a)
    res = np.linalg.solve(a, b)
    print('SOLVE: ', res)

    u = res[:m]
    v = res[m:]
    return u, v


def check_potentials(c, u, v, J):
    max_val = -10 ** 10
    max_val_pos = (-1, -1)
    for i, u_val in enumerate(u):
        for j, v_val in enumerate(v):
            if (i, j) not in J and u_val + v_val > c[i][j] and u_val + v_val - c[i][j] > max_val:
                max_val = u_val + v_val - c[i][j]
                max_val_pos = (i, j)
    print('Max potential diff:', max_val)
    return max_val_pos


def build_tree(x, J):
    m, n = np.shape(x)
    g = [[] for _ in range(m * n)]

    for i in range(m):
        for j in range(n):
            if (i, j) not in J:
                continue
            for k in range(j + 1, n):
                if (i, k) in J:
                    g[n * i + j].append(n * i + k)
                    g[n * i + k].append(n * i + j)
                    break
            for k in range(i + 1, m):
                if (k, j) in J:
                    g[n * i + j].append(n * k + j)
                    g[n * k + j].append(n * i + j)
                    break

    print(g)
    return g


def find_nearest(i, j, J):
    row = [pos for pos in J if pos[0] == i and pos[1] != j]
    col = [pos for pos in J if pos[1] == j and pos[0] != i]

    min_row_dist = 10 ** 10
    nearest_row_pos = (i, j)
    for row_pos in row:
        if abs(row_pos[1] - j) < min_row_dist:
            min_row_dist = abs(row_pos[1] - j)
            nearest_row_pos = row_pos

    min_col_dist = 10 ** 10
    nearest_col_pos = (i, j)
    for col_pos in col:
        if abs(col_pos[0] - i) < min_col_dist:
            min_col_dist = abs(col_pos[0] - i)
            nearest_col_pos = col_pos

    return nearest_row_pos, nearest_col_pos


def find_path(g, nearest_row_pos, nearest_col_pos, size):
    m, n = size

    def bfs(v, to):
        q = []
        q.append(v)
        used = [False for _ in range(m * n)]
        p = [0 for _ in range(m * n)]
        d = [0 for _ in range(m * n)]
        p[v] = -1

        print('v: {}, to: {}'.format(v, to))
        used[v] = True

        while len(q):
            v = q[-1]
            q.pop()
            for x in g[v]:
                if used[x]:
                    continue
                used[x] = True
                q.append(x)
                d[x] = d[v] + 1
                p[x] = v

        path = []
        v = to
        while v != -1:
            path.append(v)
            v = p[v]

        return path

    start = nearest_row_pos[0] * n + nearest_row_pos[1]
    end = nearest_col_pos[0] * n + nearest_col_pos[1]

    # from start to end
    path = bfs(start, end)
    print('path:', path)
    return path


def get_side_path_positions(path):
    k = 0
    new_path = []
    while k < len(path):
        pos = path[k]

        while k < len(path) and path[k][0] == pos[0]:
            k += 1

        if k < len(path):
            pos = path[k]
            new_path.append(path[k - 1])

        while k < len(path) and path[k][1] == pos[1]:
            k += 1
        if k < len(path):
            new_path.append(path[k - 1])

        if k >= len(path) and not \
                (path[-1][0] == path[-2][0] and path[-1][0] == path[0][0] or \
                 path[-1][1] == path[-2][1] and path[-1][1] == path[0][1]):
            new_path.append(path[-1])
            break
    return new_path


def update_path(x, path, J, new_pos):
    m, n = np.shape(x)
    x_new = np.copy(x)

    # return flat coordinates back to 2D
    path_extended = [(pos // n, pos - n * (pos // n)) for pos in path]

    path_extended = [new_pos] + path_extended
    print('\nPath extended:', path_extended)
    side_path = get_side_path_positions(path_extended)
    path_extended = side_path
    print('New path:', side_path)
    print()
    odd_positions = []
    for i in range(1, len(path_extended) // 2 + 1, 2):
        odd_positions.append(path_extended[i])
        if len(path) - i != i:
            odd_positions.append(path_extended[-i])
    # odd_positions = path_extended[1::2]
    print('Odd positions:', odd_positions)

    min_odd_pos_val = 10 ** 10
    min_odd_pos = (-1, -1)

    for i, j in odd_positions:
        # print(i, j, x[i][j])
        if x[i][j] < min_odd_pos_val:
            min_odd_pos_val = x[i][j]
            min_odd_pos = (i, j)

    print('Min odd pos value:', min_odd_pos_val)

    for i, j in path_extended:
        # print((i, j), (i, j) in odd_positions)
        if (i, j) in odd_positions:
            x_new[i][j] -= min_odd_pos_val
        else:
            x_new[i][j] += min_odd_pos_val

    J_new = []
    for i, j in J:
        if (i, j) != min_odd_pos:
            J_new.append((i, j))

    J_new.append(new_pos)
    return x_new, J_new


def iterations(x, J, c, iteration=0):
    if iteration == 100:
        raise OverflowError('Iteration limit reached')

    print('\nITERATION #{}\n'.format(iteration))
    m, n = np.shape(c)
    u, v = get_potentials(x, c, J)
    print(u, v)

    new_i, new_j = check_potentials(c, u, v, J)
    if new_i == -1 and new_j == -1:
        print('Soluition found: \nx = {}, \nJ = {}'.format(x, J))
        return x, J

    print('next:', new_i, new_j)
    tree = build_tree(x, J)
    nearest_row_pos, nearest_col_pos = find_nearest(new_i, new_j, J)
    print(nearest_row_pos, nearest_col_pos)
    path = find_path(tree, nearest_row_pos, nearest_col_pos, (m, n))
    print('Path:', path)
    x, J = update_path(x, path, J, (new_i, new_j))
    print('New x: {}, new J: {}'.format(x, J))
    return iterations(x, J, c, iteration + 1)


# matrix transport problem
def solve_mtp(a, b, c):
    if sum(a) != sum(b):
        a, b, c = extend(a, b, c)
    x, J = build_X_north_west(a, b)
    print('North west method returned: \nx = {}, \nJ = {}'.format(x, J))
    x, J = iterations(x, J, c)
    s = 0
    for i in range(len(x)):
        for j in range(len(x[i])):
            s += x[i][j] * c[i][j]
    print(c)
    print(s)
    return x, J

# a = [100, 300, 300]
# b = [300, 200, 200]
# c = [[8, 4, 1],
#          [8, 4, 3],
#          [9, 7, 5]]
# a = [50, 70, 80, 100, 110, 200, 250]
# b = [20, 80, 90, 90, 130, 150, 300]
# c = np.array([[5, 6, 11, 4, 9, 13, 10],
#              [3, 7, 8, 1, 12, 9, 8],
#              [10, 4, 9, 7, 3, 4, 5],
#              [2, 6, 8, 3, 7, 19, 2],
#              [7, 9, 11, 6, 4, 3, 8],
#              [2, 3, 7, 16, 14, 5, 1],
#              [17, 6, 2, 5, 6, 2, 8]])
a = [50, 70, 80, 100, 110]
b = [20, 80, 90, 90, 130]
c = np.array([[5, 6, 11, 4, 9],
             [3, 7, 8, 1, 12],
             [10, 4, 9, 7, 3],
             [2, 6, 8, 3, 7],
             [7, 9, 11, 6, 4]])
x, J = solve_mtp(a, b, c)

North west method returned: 
x = [[ 20.  30.   0.   0.   0.]
 [  0.  50.  20.   0.   0.]
 [  0.   0.  70.  10.   0.]
 [  0.   0.   0.  80.  20.]
 [  0.   0.   0.   0. 110.]], 
J = [(0, 0), (0, 1), (1, 1), (1, 2), (2, 2), (2, 3), (3, 3), (3, 4), (4, 4)]

ITERATION #0

u[0] + v[0] = 5
u[0] + v[1] = 6
u[1] + v[1] = 7
u[1] + v[2] = 8
u[2] + v[2] = 9
u[2] + v[3] = 7
u[3] + v[3] = 3
u[3] + v[4] = 7
u[4] + v[4] = 4
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
SOLVE:  [ 0.  1.  2. -2. -5.  5.  6.  7.  5.  9.]
[ 0.  1.  2. -2. -5.] [5. 6. 7. 5. 9.]
Max potential diff: 8.0
next: 2 4
[[1], [0, 6], [], [], [], [], [1, 7], [6, 12], [], [], [], [], [7, 13], [12, 18], [], [], [], [], [13, 19], [18, 24], [], [], [], [], 

In [108]:
q = np.ones([5, 5])
t = np.zeros([5])

q[:, 3] = np.zeros(len(q))
print(q)

[[1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1.]]
