In [1]:
import numpy as np

### Лабораторная №1

In [2]:
def inv_alg(A1, x, i):
    n = A1.shape[0]
    i -= 1

    l = A1 @ x
    if l[i] == 0:
        return 'The matrix is irreversible'
    _l = l.copy()
    _l[i] = -1

    l_check = (-1 / l[i]) * _l

    E = np.eye(n)
    Q = E.copy()
    Q[:, i] = l_check.T

    A1_res = np.zeros([n, n])
    for k in range(n):
        for j in range(n):
            A1_res[j][k] = Q[j][j] * A1[j][k] + Q[j][i] * A1[i][k]
            if j == i:
                A1_res[j][k] /= 2
                
    return A1_res

# A = np.array([[1, -1, 0],
#              [0, 1, 0],
#              [0, 0, 1]])
# A1 = np.array([[1, 1, 0],
#              [0, 1, 0],
#              [0, 0, 1]])
# x_A1 = np.array([[1],
#             [0],
#             [1]])
# i_A1 = 3

A = np.array([[1, 0, 0],
             [0, 1, 0],
             [0, 0, 1]])
A1 = np.array([[1, 0, 0],
             [0, 1, 0],
             [0, 0, 1]])
x_A1 = np.array([[-1],
            [1],
            [0]])
i_A1 = 2

B = np.array([[1, 3, 2],
             [4, 0, 6],
             [0, 1, 1]])
B1 = np.array([[0.6, 0.1, -1.8],
             [0.4, -0.1, -0.2],
             [-0.4, 0.1, 1.2]])
x_B1 = np.array([[1],
            [2],
            [0]])
i_B1 = 2

_A = A.copy()
_A[:, i_A1-1] = x_A1.T
print(f'With numpy:\n{np.linalg.inv(_A)}')
print(f'With algorithm:\n{inv_alg(A1, x_A1, i_A1)}')

_B = B.copy()
_B[:, i_B1-1] = x_B1.T
print(f'With numpy:\n{np.linalg.inv(_B)}')
print(f'With algorithm:\n{inv_alg(B1, x_B1, i_B1)}')

With numpy:
[[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
With algorithm:
[[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
With numpy:
[[-1.   0.5 -1. ]
 [ 2.  -0.5 -1. ]
 [ 0.   0.   1. ]]
With algorithm:
[[-1.   0.5 -1. ]
 [ 2.  -0.5 -1. ]
 [ 0.   0.   1. ]]


### Лабораторная №2

In [3]:
def simplex_main(c, A, b, x, _J):
    m = len(A)
    J = _J.copy()
    #STEP 1
    A_b = np.zeros([m, m])
    for i in range(len(J)):
        A_b[:, i] = A[:, J[i]-1]
    print(f'Step1: A_b:\n{A_b}')
    iteration = 1
    
    #STEP 2
    A_b_inv = np.linalg.inv(A_b)
    print(f'\nStep2: A_b_inv:\n{A_b_inv}')
    
    while True:
        #STEP 3
        print(f'Iteration №{iteration}:\n')
        c_b = np.array([c[J[i]-1] for i in range(len(J))])
        print(f'Step3: c_b={c_b}')
        
        #STEP 4
        u = c_b @ A_b_inv
        print(f'Step4: u={u}')
        
        #STEP 5
        delta = u @ A - c #repeat while all delta[i] become >= 0
        print(f'Step5: delta={delta}')        
        if min(delta) >= 0:
            #return f'Answer:{x}, J:{J}'
            return x, J
        
        #STEP 6
        for d in delta:
            if d < 0:
                j0 = list(delta).index(d)
                break

        z = np.zeros(len(J))
        z = A_b_inv @ A[:, j0]
        print(f'Step6: z={z}') 
        
        #STEP 7
        t = np.zeros(len(J))
        for i in range(len(J)):
            if z[i] > 0:
                t[i] = x[J[i]-1] / z[i]
            else:
                t[i] = np.inf
        t0 = min(t)
        print(f'Step7: t={t}; t0={t0}')
        if t0 == np.inf:
            return 'TARGET FUNCTION IS UNBOUNDED'
        
        #STEP 8
        t_index_for_j = list(t).index(t0)

        x_prev = x.copy()
        x = np.zeros(len(A[0]))
        
        J[t_index_for_j] = j0 + 1
        
        for i in range(len(J)):
            x[J[i] - 1] = x_prev[J[i] - 1] - t0 * z[i]
        print(f'x_before:{x_prev}')
        x[j0] =  t0
        
        A_b_prev = A_b.copy()
        A_b[:, t_index_for_j] = A[:, j0]
        A_b_inv = inv_alg(np.linalg.inv(A_b_prev), A[:, j0], t_index_for_j + 1)
        
        print(f'Step8:\n t={t}, x={x}, J={J}, z={z}')
        print(f'A_b_inv:\n{A_b_inv}')
        print('##############')
        iteration += 1


#m, n = 4, 6
# A = np.array([[1, 2, 1, 0, 0, 0],
#              [2, 1, 0, 1, 0 ,0],
#              [1, 0, 0, 0, 1, 0],
#              [0, 1, 0, 0, 0, 1]])
# b = np.array([10, 11, 5, 4])
# c = np.array([20, 26, 0, 0, 0, 1])
# x = np.array([2, 4, 0, 3, 3, 0])
# J = np.array([5, 2, 1, 4])

# A = np.array([[-1, 1, 1, 0, 0],
#              [1, 0, 0, 1, 0],
#              [0, 1, 0, 0, 1]])
# b = np.array([1, 3, 2])
# c = np.array([1, 1, 0, 0, 0])
# x = np.array([0, 0, 1, 3, 2])
# J = np.array([3, 4, 5])

A = np.array([[2, 1, 1, 0, 0, 0],
             [1, 4, 0, 1, 0, 0],
             [1, 0, 0, 0, 1, 0],
             [0, 1, 0, 0, 0, 1]])
b = np.array([20, 24, 9, 5])
c = np.array([22, 21, 1, 0, 0, 0])
x = np.array([0, 0, 20, 24, 9, 5])
J = np.array([3, 4, 5, 6])
print(simplex_main(c, A, b, x, J))

Step1: A_b:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Step2: A_b_inv:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Iteration №1:

Step3: c_b=[1 0 0 0]
Step4: u=[1. 0. 0. 0.]
Step5: delta=[-20. -20.   0.   0.   0.   0.]
Step6: z=[2. 1. 1. 0.]
Step7: t=[10. 24.  9. inf]; t0=9.0
x_before:[ 0  0 20 24  9  5]
Step8:
 t=[10. 24.  9. inf], x=[ 9.  0.  2. 15.  0.  5.], J=[3 4 1 6], z=[2. 1. 1. 0.]
A_b_inv:
[[ 1.  0. -2.  0.]
 [ 0.  1. -1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
##############
Iteration №2:

Step3: c_b=[ 1  0 22  0]
Step4: u=[ 1.  0. 20.  0.]
Step5: delta=[  0. -20.   0.   0.  20.   0.]
Step6: z=[1. 4. 0. 1.]
Step7: t=[2.   3.75  inf 5.  ]; t0=2.0
x_before:[ 9.  0.  2. 15.  0.  5.]
Step8:
 t=[2.   3.75  inf 5.  ], x=[9. 2. 0. 7. 0. 3.], J=[2 4 1 6], z=[1. 4. 0. 1.]
A_b_inv:
[[ 1.  0. -2.  0.]
 [-4.  1.  7.  0.]
 [ 0.  0.  1.  0.]
 [-1.  0.  2.  1.]]
##############
Iteration №3:

Step3: c_b=[21  0 22  0]
Step4: u=[ 21.   0. -20.   0.]
Step

### Лабораторная №3

In [11]:
# A = np.array([[2, 1, 1, 0, 0, 0],
#              [1, 4, 0, 1, 0, 0],
#              [1, 0, 0, 0, 1, 0],
#              [0, 1, 0, 0, 0, 1]])
# b = np.array([20, 24, 9, 5])
# c = np.array([22, 21, 1, 0, 0, 0])
# A = np.array([[2, 1, 1, 0, 0, 0],
#              [1, 3, 0, 1, 0, 0],
#              [1, 0, 0, 0, 1, 0],
#              [0, 1, 0, 0, 0, 1]])
# b = np.array([22, 21, 10, 6])
# c = np.array([20, 19, 0, 0, 0, -1])
A = np.array([[1, 1, 1],
            [2, 2, 2]])
b = np.array([0, -1])
c = np.array([1, 0, 0])
#22
# A = np.array([[-2, 3, 1, 0],
#              [4, 3, 0, 1],
#              [0, 9, 2, 1]])
# b = np.array([6, 24, 36])
#20
# A = np.array([[-1, 3, 1, 0, 0],
#              [1, 1, 0, 1, 0],
#              [0, -1, 0, 0, 1]])
# b = np.array([3, 5, -3])
#21
# A = np.array([[-1, 3, 1, 0],
#              [3, 2, 0, 1],
#              [1, 8, 2, 1]])
# b = np.array([6, 15, 27])
# print(f'A:\n{A}')
# print(f'b:\n{b}')
#28
# A = np.array([[-1, 6, 1, 0],
#              [4, 1, 0, 1],
#              [3, 7, 1, 1]])
# b = np.array([18, 28, 46])


def simplex_begin(A, b):
    for i in range(len(b)):
        if b[i] < 0:
            A[i] *= -1
            b[i] *= -1
            
    n = len(A[0])    
    m = len(b)
    J = np.array([i + 1 for i in range(n)])
    _c, _A, _x, _J, E = np.zeros(n + len(A)), A.copy(), np.zeros(n), \
                        np.array([]),  np.eye(len(A))

    _A, _x = np.concatenate((_A, E), axis=1), np.concatenate((_x, b))
    print(f'_x={_x}')
    for i in range(len(A)):
        _c[n + i] = -1   

    for i in range(1, len(A) + 1):
        index = n + i
        _J = np.append(_J, index)
    print(f'_J:{_J}')
    _J = [int(_J[i]) for i in range(len(_J))]
    
    x_new, J_new = simplex_main(_c, _A, b, _x, _J)

    if not np.all(x_new[-m:] == 0):
        return f'PROBLEM IS NOT FEASIBLE: x:{x_new}'

    x_result = x_new[:n]
    print(f'x_new:{x_new}')
    print(f'x_result:{x_result}')
    print(f'J_new:{J_new}, _J:{_J}')
    if not set(J_new) & set(_J):
        return f'Answer is:\n J:{J_new},\n A*:\n{A},\n x*:{x_result}'
    else:
        J_art = np.array([])
        J_not_basis = J.copy()
        A_result = A.copy()
        _A_result = _A.copy()
        _c_result = _c.copy()    
        for j in J_new:
            if j not in J:
                J_art = np.append(J_art, j)
            if j in J:
                J_not_basis = np.setdiff1d(J_not_basis, j)
        it = 1
        for i in range(len(J_art)):
            print(f'\nIteration {it}:')
            k = list(J_new).index(J_art[i])

            l = np.zeros((len(J_new), len(J_new)))
            A_art_basis = np.zeros([len(J_new), len(J_new)])
            for i in range(len(J_new)):
                A_art_basis[:, i] = _A[:, J_new[i] - 1]

            A_art_basis_inv = np.linalg.inv(A_art_basis)
            print(f'_A:\n{_A}')
            print(f'A_art_basis:\n{A_art_basis}')
            print(f'A_art_basis_inv:\n{A_art_basis_inv}')
            for i in range(len(J_not_basis)):
                l[i] = A_art_basis_inv @ _A[:, J_not_basis[i] - 1]
                print(f'_A[:, J_not_basis[i] - 1]={_A[:, J_not_basis[i] - 1]}')
                print(f'l[i]={l[i]}')
            #print(l[:, 0][0])

            index = 0
            check = np.zeros(len(l))
            for vector in l:
                if vector[k] != 0:
                    J_new[k] = J_not_basis[index]   
                    check[index] = 1
                index += 1    
            if np.all(check == 0):
                J_new = np.delete(J_new, k)
                A_result = np.delete(A_result, k, axis = 0)
                _A_result = np.delete(_A_result, k, axis = 0)
                _c_result = np.delete(_c_result, n + k)
            if not set(J_new) & set(_J):
                return f'Answer:\n J:{J_new},\n A*:\n{A_result},\n x*:{x_result}'                
            
print(simplex_begin(A, b))

_x=[0. 0. 0. 0. 1.]
_J:[4. 5.]
Step1: A_b:
[[1. 0.]
 [0. 1.]]

Step2: A_b_inv:
[[1. 0.]
 [0. 1.]]
Iteration №1:

Step3: c_b=[-1. -1.]
Step4: u=[-1. -1.]
Step5: delta=[1. 1. 1. 0. 0.]
PROBLEM IS NOT FEASIBLE: x:[0. 0. 0. 0. 1.]


### Лабораторная №4

In [5]:
def dual_simplex(A, b, c, J):
    #prepare
    m = len(A)
    n = len(A[0])
    A_b = np.zeros([m, m])
    for i in range(len(J)):
        A_b[:, i] = A[:, J[i] - 1]

    A_b_inv = np.linalg.inv(A_b)
    c_b = np.array([c[J[i]-1] for i in range(len(J))])
    y = c_b @ A_b_inv
    print(f'A_b:\n{A_b}')
    print(f'A_b_inv:\n{A_b_inv}')
    print(f'c_b={c_b}')
    print(f'y={y}')

    it = 1
    while True:
        print(f'\nIteration = {it}')
        #STEP 1
        print(f'A_b_inv:\n{A_b_inv}')
        ae = np.zeros(n)
        ae_b = A_b_inv @ b
        for i in range(len(ae_b)):
            ae[J[i] - 1] = ae_b[i]

        if min(ae) >= 0:
            return(f'Answer: {ae}') 
        print(f'ae = {ae}')
        
        loc_min = min(ae)
        
        ind = list(ae).index(loc_min) + 1
        
        print(ind)
        index_of_row = list(J).index(ind)
        print(f'index_of_row = {index_of_row+1}')
        delta_y = A_b_inv[index_of_row]
        print(f'delta_y = {delta_y}')

        #STEP 2
        indexes = np.arange(n) + 1
        J_nb = np.array([])
        for i in indexes:
            if i not in J:
                J_nb = np.append(J_nb, i)
        print(f'J_nb = {J_nb}')
        mu = np.array([delta_y @ A[:, int(J_nb[i]) - 1] for i in range(len(J_nb))])
        print(f'mu = {mu}')
        
        #STEP 3
        if min(mu) >= 0:
            return 'no solutions' 

        sigma = []
        sigma_indx = []
        
        for i in range(len(mu)):
            if mu[i] < 0:
                j = int(J_nb[i] - 1)
                sgm = (c[j] - A[:, j] @ y) / mu[i]
                sigma.append(sgm)
                sigma_indx.append(j)
        print(f'sigma = {sigma}')
        sgm0 = min(sigma)
        j_indx = sigma.index(sgm0)
        index_sgm0 = sigma_indx[j_indx] + 1
        print(f'index_sgm0 = {index_sgm0}')

        #STEP 4
        J[index_of_row] = index_sgm0
        y += sgm0 * delta_y
        print(f'y = {y}')
        print(f'J = {J}')
        for i in range(len(J)):
            A_b[:, i] = A[:, J[i] - 1]
        print(f'A_b:\n{A_b}')
        A_b_inv = np.linalg.inv(A_b)
        print(f'A_b_inv:\n{A_b_inv}')       
        it += 1

c = np.array([-4, 2, 0, 1])
A = np.array([[-1, -3, 1, 1],
             [-2, 3, 0, 1]])

b = np.array([-12, -6])
J = np.array([3, 4])

print(double_simplex(A, b, c, J))

A_b:
[[1. 1.]
 [0. 1.]]
A_b_inv:
[[ 1. -1.]
 [ 0.  1.]]
c_b=[0 1]
y=[0. 1.]

Iteration = 1
A_b_inv:
[[ 1. -1.]
 [ 0.  1.]]
ae = [ 0.  0. -6. -6.]
3
index_of_row = 1
delta_y = [ 1. -1.]
J_nb = [1. 2.]
mu = [ 1. -6.]
sigma = [0.16666666666666666]
index_sgm0 = 2
y = [0.16666667 0.83333333]
J = [2 4]
A_b:
[[-3.  1.]
 [ 3.  1.]]
A_b_inv:
[[-0.16666667  0.16666667]
 [ 0.5         0.5       ]]

Iteration = 2
A_b_inv:
[[-0.16666667  0.16666667]
 [ 0.5         0.5       ]]
ae = [ 0.  1.  0. -9.]
4
index_of_row = 2
delta_y = [0.5 0.5]
J_nb = [1. 3.]
mu = [-1.5  0.5]
sigma = [1.4444444444444444]
index_sgm0 = 1
y = [0.88888889 1.55555556]
J = [2 1]
A_b:
[[-3. -1.]
 [ 3. -2.]]
A_b_inv:
[[-0.22222222  0.11111111]
 [-0.33333333 -0.33333333]]

Iteration = 3
A_b_inv:
[[-0.22222222  0.11111111]
 [-0.33333333 -0.33333333]]
Answer: [6. 2. 0. 0.]


### Лабораторная №5 

In [21]:
# a = [100, 300, 300]
# b = [300, 200, 200]
# c = np.array([[8, 4, 1],
#              [8, 4, 3],
#              [9, 7, 5]])
# a = [50, 70, 80, 100, 110, 200, 250]
# b = [20, 80, 90, 90, 130, 150, 300]
# c = np.array([[5, 6, 11, 4, 9, 13, 10],
#              [3, 7, 8, 1, 12, 9, 8],
#              [10, 4, 9, 7, 3, 4, 5],
#              [2, 6, 8, 3, 7, 19, 2],
#              [7, 9, 11, 6, 4, 3, 8],
#              [2, 3, 7, 16, 14, 5, 1],
#              [17, 6, 2, 5, 6, 2, 8]])

#5(mine)
# a = [50, 70, 80]
# b = [20, 90, 90]
# c = np.array([[5, 6, 11],
#              [3, 7, 8],
#              [10, 4, 9]])

#14
# a = [100, 70, 170]
# b = [140, 100, 100]
# c = np.array([[1, 5, 6],
#              [2, 3, 2],
#              [4, 1, 1]])

#11
# a = [50, 170, 80]
# b = [200, 50, 50]
# c = np.array([[2, 5, 6],
#              [3, 4, 3],
#              [6, 1, 2]])
def transport_problem(a, b, c):
    m, n = len(a), len(b)
    X = np.zeros([m, n])
    J = []
    i, j = 0, 0
    
    #PHASE 1
    while True:
#         if sum(a) == 0 and sum(b) == 0:
#             break
        
        if a[i] < b[j] or (j == n-1 and i <= m-1):
            X[i][j] = a[i]
            b[j] -= a[i]
            a[i] = 0
            J.append([i, j])
            i += 1
        else:
            X[i][j] = b[j]
            a[i] -= b[j]
            b[j] = 0
            J.append([i, j])
            j += 1
        if i == m and j == n-1:
            break
    print(f'J:{J}')
    print(f'X before 2nd phase:\n{X}')        
    #PHASE 2
    it = 1
    while True:
        print(f'\nIteration {it}\n')
        UV = np.zeros([n + m, n + m])
        for i in range(len(J)):
            UV[i][J[i][0]] = 1    
            UV[i][J[i][1] + m] = 1
        UV[-1][0] = 1
        print(f'UV:\n{UV}')
        b_uv = [c[J[i][0]][J[i][1]] for i in range(len(J))]   
        print(f'b_uv:{b_uv}')
        b_uv.append(0)
        print(f'b_uv:{b_uv}')
        uv = np.linalg.solve(UV, b_uv)
        u = uv[:m]
        v = uv[-n:]
        print(f'u:{u}; v:{v}')
        positions = []
        for i in range(m):
            for j in range(n):
                positions.append([i, j])

        J_not_basis = []
        for p in positions:
            if p not in J:
                J_not_basis.append(p)
        print(f'J_not_basis:{J_not_basis}')
        pos = []
        quit = True
        for p in J_not_basis:
            if u[p[0]] + v[p[1]] > c[p[0]][p[1]]:
                quit = False
                pos = p
                break
        print(pos)
        if quit:
            print(f'Answer:')
            return X
            

        for p in J:
            if n * p[0] + 1 + p[1] > n * pos[0] + 1 + pos[1]: #n or m?
                index = J.index(p)
                temp_pos = pos.copy()
                J.insert(index, temp_pos)
                print(f'J with new pos:{J}')
                break

        #здесь ненужные строки/столбцы будут обнулятся
        #вместо удаления (это нужно для правильного определения позиции)
        basis_matrix = np.zeros([m, n])
        for p in J:
            basis_matrix[p[0]][p[1]] = 1

        
        #для видимого удаления строк/столбцов
        basis_matrix_copy = basis_matrix.copy()
        print(f'before del:\n{basis_matrix_copy}')
        deleted = False
        while True:
            deleted = False
            for i in range(len(basis_matrix)):
                if 0 < sum(basis_matrix[i]) < 2:
                    basis_matrix[i] = np.zeros(len(basis_matrix[0]))
                    deleted = True
                    break
            for i in range(len(basis_matrix[0])):
                 if 0 < sum(basis_matrix[:, i]) < 2:
                    basis_matrix[:, i] = np.zeros(len(basis_matrix))
                    deleted = True
                    break
            if not deleted:
                break
        deleted = False
        t_pos = []
        while True:
            deleted = False
            for i in range(len(basis_matrix_copy)):
                if 0 < sum(basis_matrix_copy[i]) < 2:
                    basis_matrix_copy = np.delete(basis_matrix_copy, i, axis=0)
                    deleted = True
                    break
            for i in range(len(basis_matrix_copy[0])):
                 if 0 < sum(basis_matrix_copy[:, i]) < 2:
                    basis_matrix_copy = np.delete(basis_matrix_copy, i, axis=1)                
                    deleted = True
                    break
            if not deleted:
                break
        print(f'after del:\n{basis_matrix_copy}')
        print(f'basis_matrix:\n{basis_matrix}')
        J_angle = []
        for i in range(len(basis_matrix)):
            for j in range(len(basis_matrix[0])):
                if basis_matrix[i][j] == 1:
                    J_angle.append([i, j])
        print(f'J angle only:\n{J_angle}')

        sign_matrix = np.full(basis_matrix.shape, '.')
        sign_matrix[pos[0]][pos[1]] = '+'
        cur_pos = pos
        print(f'pos={pos}')
        going_column = True
        all_signs = ['+']
        all_minus = []
        for i in range(len(J_angle)):
            while True:            
                for p in J_angle:
                    if (p[0] == cur_pos[0] and p[1] != cur_pos[1] or p[0] != cur_pos[0] and p[1] == cur_pos[1]) \
                        and sign_matrix[p[0]][p[1]] == '.':
                        cur_pos = p
                        print(cur_pos)
                        if all_signs[-1] == '+':
                            sign_matrix[cur_pos[0]][cur_pos[1]] = '-'
                            all_signs.append('-')
                            all_minus.append(X[cur_pos[0]][cur_pos[1]])
                        else:
                            sign_matrix[cur_pos[0]][cur_pos[1]] = '+'
                            all_signs.append('+')                    
                        break
                break

        print(f'all_minus:{all_minus}')
        teta = min(all_minus)
        print(f'teta:{teta}')
        print(f'sign_matrix:\n{sign_matrix}')
        for i in range(len(X)):
            for j in range(len(X[0])):
                if sign_matrix[i][j] == '-':
                    X[i][j] -= teta
                if sign_matrix[i][j] == '+':
                    X[i][j] += teta
        finish = False
        print(f'new X:\n{X}')
        for i in range(len(X)):
            for j in range(len(X[0])):
                if X[i][j] == 0 and [i, j] in J:
                    pos_min = [i, j]
                    J.remove(pos_min)
                    finish = True
                    break
            if finish:
                break

        print(f'new J: {J}')
        it += 1

#5(mine)
a = [0, 0, 0]
b = [0, 0, 0]
c = np.array([[0, 0, 0],
             [0, 0, 0],
             [0, 0, 0]])
transport_problem(a, b, c)



J:[[0, 0], [0, 1], [0, 2], [1, 2], [2, 2]]
X before 2nd phase:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Iteration 1

UV:
[[1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]
b_uv:[0, 0, 0, 0, 0]
b_uv:[0, 0, 0, 0, 0, 0]
u:[0. 0. 0.]; v:[-0. -0. -0.]
J_not_basis:[[1, 0], [1, 1], [2, 0], [2, 1]]
[]
Answer:


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Лабораторная работа №6

In [26]:
import itertools as itrt

# c = np.array([-8, -6, -4, -6])
# D = np.array([[2, 1, 1, 0],
#              [1, 1, 0, 0],
#              [1, 0, 1, 0],
#              [0, 0, 0, 0]])
# A = np.array([[1, 0, 2, 1],
#              [0, 1, -1, 2]])
# x = np.array([2, 3, 0, 0])
# J = np.array([1, 2]) #not python index
# J_adv = np.array([1, 2]) #not python index

def square_task(c, D, A, x, J, J_adv):
    m = len(A)
    n = len(A[0])
    itr = 1
    while True:
        print(f'\nIteration {itr}:\n')
        #STEP 1
        print(f'x:{x}')
        cx = c + x @ D
        print(f'cx:{cx}')
        cbx = np.array([cx[J[i] - 1] for i in range(len(J))])

        A_b = np.array([(A[:, J[i] - 1]) for i in range(len(J))])
        A_b_inv = np.linalg.inv(A_b)
        print(f'A_b_inv:\n{A_b_inv}')
        ux = -cbx @ A_b_inv
        print(f'ux:{ux}')
        deltax = ux @ A + cx
        print(f'deltax:{deltax}')
        #STEP 2
        if min(deltax) >= 0:
            return f'ANSWER:{x}' #return

        #STEP 3
        j0 = list(deltax).index(min(deltax)) #python index
        print(f'j0:{j0}')
        #STEP 4
        l = np.zeros(n)
        l[j0] = 1
        print(f'J_adv:{J_adv}')
        l_adv = np.delete(l, J_adv - 1, axis=0)
        print(f'l_adv:{l_adv}')

        #STEP 4.a
        #all linear combinations of J(coordinates of Ds elements)
        D_adv_indx = list(itrt.combinations_with_replacement(J_adv - 1, 2))
        lJ = len(J_adv)
        D_adv = np.zeros([lJ, lJ])
        k = 0
        for i in range(lJ):
            for j in range(i, lJ):
                if D_adv_indx[k][0] != D_adv_indx[k][1]:
                    D_adv[j][i] = D[D_adv_indx[k][1]][D_adv_indx[k][0]]
                D_adv[i][j] = D[D_adv_indx[k][0]][D_adv_indx[k][1]]
                k += 1

        A_adv_b = np.array([(A[:, J_adv[i] - 1]) for i in range(len(J_adv))])
        At_adv_b = np.transpose(A_adv_b)
        print(f'D_adv:\n{D_adv}')
        print(f'A_adv_b:\n{A_adv_b}')
        
        Matrix1 = np.row_stack((D_adv, At_adv_b))
        Matrix2 = np.row_stack((A_adv_b, np.zeros([len(A_adv_b[0]), len(At_adv_b)])))
        H = np.column_stack((Matrix1, Matrix2))

        #STEP 4.b
        b_up = np.array([D[:, j0][J_adv[i] - 1] for i in range(len(J_adv))])
        print(f'b_up:{b_up}')
        b_down = A[:, j0]
        print(f'b_down:{b_down}')
        b = np.concatenate((b_up, b_down))

        #STEP 4.c
        print(f'H:\n{H}')
        print(f'b:{b}')
        x_hb = -np.linalg.inv(H) @ b 
        print(f'x_hb:{x_hb}')
        ladv = np.array([x_hb[i] for i in range(len(J_adv))])
        print(f'ladv:{ladv}')
        l = np.concatenate((ladv, l_adv))

        #STEP 5
        print(f'l:{l}')
        print(f'D:\n{D}')
        
        delta = l @ D @ l[:, np.newaxis]
        print(f'delta:{delta}')
        
        teta = np.full(len(J_adv), np.inf)
        teta_j0 = np.inf
        if delta > 0:
            teta_j0 = abs(deltax[j0]) / delta
        print(f'teta_j0:{teta_j0}')
        
        for i in range(len(teta)):
            if l[i] < 0:
                teta[i] = -x[i] / l[i]
        teta = np.append(teta, teta_j0)
        print(f'teta:{teta}')
        
        teta0 = min(teta)
        print(f'teta0:{teta0}')
        
        if teta0 == np.inf or teta0 > 1e+16:
            return ('TARGET FUNCTION IS UNBOUNDED') #return
        
        js = j0 #j*
        if teta0 != teta_j0:
            js = J_adv[list(teta).index(teta0)] - 1 #python index
        print(f'js:{js}')
        
        #STEP 6(UPDATE)
        x = x + teta0 * l
        print(f'teta0 * l:{teta0 * l}')
        print(f'J:{J}, J_adv:{J_adv}')
        
        last_condition = True
        if js == j0:
            J_adv = np.append(J_adv, js + 1)
            last_condition = False
        elif js + 1 in J_adv and js+1 not in J:
            J_adv = np.delete(J_adv, np.where(J_adv == js + 1))
            last_condition = False
        elif js + 1 in J:
            s = list(J).index(js + 1)
            J_adv_tmp = set(J_adv) - set(J)
            J_adv_tmp = list(J_adv_tmp)
            print(f'J_adv_tmp:{J_adv_tmp}')
            for i in range(len(J_adv_tmp)):
                j_plus = J_adv_tmp[i] #not python index
                vector_tmp = A_b_inv @ A[:, j_plus - 1]
                print(vector_tmp)
                if vector_tmp[s] != 0:
                    J = np.where(J == js + 1, j_plus, J)
                    J_adv = np.delete(J_adv, np.where(J_adv == j_plus))
                    last_condition = False
                    break
            
        if last_condition:
            J = np.where(J == js + 1, j0 + 1, J)
            J_adv = np.where(J_adv == js + 1, j0 + 1, J_adv)
        itr += 1

#5          
# c = np.array([0, -1, 0])
# D = np.array([[2, -1, 0],
#              [-1, 2, -1],
#              [0, -1, 2]])
# A = np.array([[2, 1, 0],
#              [0, 1, 2]])
# x = np.array([0, 2, 1])
# J = np.array([2, 3]) #not python index
# J_adv = np.array([2, 3]) #not python index
#11
c = np.array([0, 0, -2])
D = np.array([[1, 0, 0],
             [0, 1, -1],
             [0, -1, 2]])
A = np.array([[0, 1, 1],
             [1, 0, 1]])
x = np.array([2, 4, 0])
J = np.array([1, 2]) #not python index
J_adv = np.array([1, 2]) #not python index
print(square_task(c, D, A, x, J, J_adv)) 


Iteration 1:

x:[2 4 0]
cx:[ 2  4 -6]
A_b_inv:
[[0. 1.]
 [1. 0.]]
ux:[-4. -2.]
deltax:[  0.   0. -12.]
j0:2
J_adv:[1 2]
l_adv:[1.]
D_adv:
[[1. 0.]
 [0. 1.]]
A_adv_b:
[[0 1]
 [1 0]]
b_up:[ 0 -1]
b_down:[1 1]
H:
[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
b:[ 0 -1  1  1]
x_hb:[-1. -1.  2.  1.]
ladv:[-1. -1.]
l:[-1. -1.  1.]
D:
[[ 1  0  0]
 [ 0  1 -1]
 [ 0 -1  2]]
delta:[6.]
teta_j0:[2.]
teta:[2. 4. 2.]
teta0:2.0
js:2
teta0 * l:[-2. -2.  2.]
J:[1 2], J_adv:[1 2]

Iteration 2:

x:[0. 2. 2.]
cx:[0. 0. 0.]
A_b_inv:
[[0. 1.]
 [1. 0.]]
ux:[0. 0.]
deltax:[0. 0. 0.]
ANSWER:[0. 2. 2.]


In [27]:
q = np.array([[2, -1, -1],
             [-1,  2,  0],
             [-1,  0,  2]])
p = np.array([[1, 1],
             [0, 2],
             [2, 0]])
print(np.concatenate((q, p), axis=1))

[[ 2 -1 -1  1  1]
 [-1  2  0  0  2]
 [-1  0  2  2  0]]
